# Generated by Django 4.0.6 on 2022-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Beer Name', max_length=100)),
                ('label_URL', models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png')),
                ('beer_type', models.CharField(default='Beer Type', max_length=100)),
                ('beer_container', models.CharField(default='Draft', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brewer', models.CharField(default="Slick Daddy's Brewing", max_length=200)),
                ('description', models.TextField(default="It's a beer - we promise you'll like it.")),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4)),
                ('beer_of_the_month', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event Name', max_length=200)),
                ('url', models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='Join us for...')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Food Name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_URL', models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png')),
                ('description', models.TextField(default="It's brewery food!")),
                ('tags', models.CharField(default='Seperated by comma - ex: gluten free, vegan, dairy free', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Merch Item Name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(default='Merchandise description')),
                ('image_URL', models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png')),
                ('on_sale', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
