# Generated by Django 4.0.6 on 2022-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Beer Name', max_length=100)),
                ('label_URL', models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png')),
                ('beer_type', models.CharField(default='Beer Type', max_length=100)),
                ('beer_container', models.CharField(default='Beer Container', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brewer', models.CharField(default="Slick Daddy's Brewing", max_length=200)),
                ('description', models.TextField(default="It's a beer - we promise you'll like it.")),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
