# Generated by Django 4.0.6 on 2022-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='type',
            field=models.CharField(default='Beer Type', max_length=100),
        ),
    ]
