# Generated by Django 4.0.6 on 2022-07-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.CharField(blank=True, default='Seperated by comma - ex: gluten free, vegan, dairy free', max_length=200),
        ),
    ]
