# Generated by Django 4.0.6 on 2022-07-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_beer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='type',
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_container',
            field=models.CharField(default='Draft', max_length=100),
        ),
    ]
