# Generated by Django 4.0.6 on 2022-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_alter_event_end_alter_event_start_alter_food_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='date', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
