# Generated by Django 4.0.6 on 2022-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_tourbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
