# Generated by Django 4.0.6 on 2022-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_alter_tourbooking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='additional_info',
            field=models.CharField(blank=True, default='additional information', max_length=254),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='date',
            field=models.CharField(default='mm/dd/yyyy', max_length=10),
        ),
    ]
